// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Doors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .HasColumnType("TEXT");

                    b.Property<string>("bodyType")
                        .HasColumnType("TEXT");

                    b.Property<string>("wheel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Doors = "4",
                            Engine = "test",
                            Make = "1998",
                            Model = "Mercedes",
                            VehicleType = "Car",
                            bodyType = "hatchback",
                            wheel = "5"
                        },
                        new
                        {
                            Id = 2,
                            Doors = "4",
                            Engine = "test",
                            Make = "1998",
                            Model = "Mercedes",
                            VehicleType = "Car",
                            bodyType = "hatchback",
                            wheel = "5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
